version: '3.3'
services:
  taxi-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'taxidb'
      MYSQL_USER: 'taxiuser'
      MYSQL_PASSWORD: 'taxipwd'
      MYSQL_ROOT_PASSWORD: 'rootpwd'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"