version: '3.3'
services:
  taxi-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'taxidb'
      MYSQL_USER: 'taxiuser'
      MYSQL_PASSWORD: 'taxipwd'
      MYSQL_ROOT_PASSWORD: 'rootpwd'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  customer-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'customerdb'
      MYSQL_USER: 'customeruser'
      MYSQL_PASSWORD: 'customerpwd'
      MYSQL_ROOT_PASSWORD: 'rootpwd'
    ports:
      - '3307:3306'
    expose:
      - '3306'